/* Formatted on 23.07.2023 15:19:12 (QP5 v5.185.11230.41888) */
ALTER TABLE STUDENT
ADD TEACHER_ID NUMBER;

ALTER TABLE STUDENT
ADD CONSTRAINT FK_TEACHER_ID
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(ID);

CREATE TABLE TEACHER_LESSON
(
   ID           NUMBER PRIMARY KEY,
   TEACHER_ID   NUMBER,
   LESSON_ID    NUMBER,
   DATA_DATE    DATE DEFAULT SYSDATE,
   ACTIVE       INTEGER DEFAULT 1
);


ALTER TABLE TEACHER_LESSON
ADD CONSTRAINT FK_TEACHER_ID2
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(ID)
ADD CONSTRAINT FK_LESSON_ID
FOREIGN KEY (LESSON_ID) REFERENCES LESSON(ID);

CREATE TABLE STUDENT_TEACHER_LESSON
(
   ID                  NUMBER PRIMARY KEY,
   STUDENT_ID          NUMBER,
   TEACHER_LESSON_ID   NUMBER,
   DATA_DATE           DATE DEFAULT SYSDATE,
   ACTIVE              INTEGER DEFAULT 1
);

ALTER TABLE STUDENT_TEACHER_LESSON
ADD CONSTRAINT FK_STUDENT_TEACHER_ID
FOREIGN KEY (TEACHER_LESSON_ID) REFERENCES TEACHER_LESSON(ID)
ADD CONSTRAINT FK_STUDENT_ID2
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID);


SELECT *
  FROM STUDENT, STUDENT_ADD_INFO;

SELECT ROWNUM R,
       S.ID,
       S.NAME,
       S.SURNAME,
       SAI.UNIVERSITY,
       SAI.FACULTY,
       SAI.SPECIALITY
  FROM STUDENT S, STUDENT_ADD_INFO SAI
 WHERE S.ACTIVE = 1 AND S.ID = SAI.STUDENT_ID;