
SELECT COUNT (*) STUDENT_COUNT FROM STUDENT;


  SELECT S.NAME || ' \ ' || S.SURNAME STUDENT_NAME_AND_SURNAME,
         SUM (P.AMOUNT) SUM_AMOUNT
    FROM PAYMENT P
         INNER JOIN STUDENT_TEACHER_LESSON STL
            ON STL.ID = P.STUDENT_TEACHER_LESSON_ID
         INNER JOIN STUDENT S
            ON STL.STUDENT_ID = S.ID
   WHERE P.ACTIVE = 1
GROUP BY S.NAME, S.SURNAME
  HAVING SUM (AMOUNT) > 100;



SELECT T.ID, T.NAME TEACHER_NAME, SUM(P.AMOUNT) SUM_AMOUNT
  FROM PAYMENT P
       INNER JOIN STUDENT_TEACHER_LESSON STL
          ON STL.ID = P.STUDENT_TEACHER_LESSON_ID
       INNER JOIN TEACHER_LESSON TL
          ON STL.TEACHER_LESSON_ID = TL.ID
       INNER JOIN TEACHER T
          ON TL.TEACHER_ID = T.ID
 WHERE P.ACTIVE = 1
 GROUP BY T.ID, T.NAME;
 
 
 ALTER TABLE STUDENT
 ADD TEST1_ID NUMBER;
 
 ALTER TABLE STUDENT
 DROP COLUMN TEST1_ID;
 
  ALTER TABLE STUDENT
 ADD (TEST2_ID NUMBER,
 TEST3_ID NUMBER);
 
 ALTER TABLE STUDENT
 MODIFY TEST2_ID VARCHAR2(60);
 
  ALTER TABLE STUDENT
 RENAME COLUMN TEST2_ID TO TEST2 ;
 
 
 DESC STUDENT;