/* Formatted on 28.07.2023 12:57:14 (QP5 v5.185.11230.41888) */
CREATE OR REPLACE VIEW STUDENT_TEACHER_LESSON_VIEW
AS
   SELECT STL.ID,
          S.NAME || ' \ ' || S.SURNAME STUDENT_NAME_AND_SURNAME,
          T.NAME TEACHER_NAME,
          L.NAME LESSON_NAME
     FROM STUDENT_TEACHER_LESSON STL
          INNER JOIN STUDENT S
             ON STL.STUDENT_ID = S.ID
          INNER JOIN TEACHER_LESSON TL
             ON STL.TEACHER_LESSON_ID = TL.ID
          INNER JOIN TEACHER T
             ON TL.TEACHER_ID = T.ID
          INNER JOIN LESSON L
             ON TL.LESSON_ID = L.ID
    WHERE STL.ACTIVE = 1;

CREATE TABLE PAYMENT
(
   ID                          NUMBER PRIMARY KEY,
   STUDENT_TEACHER_LESSON_ID   NUMBER,
   AMOUNT                      FLOAT,
   DATA_DATE                   DATE DEFAULT SYSDATE,
   ACTIVE                      INTEGER DEFAULT 1
);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_STUDENT_TEACHER_LESSON_ID
FOREIGN KEY (STUDENT_TEACHER_LESSON_ID) REFERENCES STUDENT_TEACHER_LESSON(ID);



CREATE OR REPLACE VIEW PAYMENT_VIEW
AS
   SELECT P.ID,
          S.NAME || ' \ ' || S.SURNAME STUDENT_NAME_AND_SURNAME,
          T.NAME TEACHER_NAME,
          L.NAME LESSON_NAME,
          P.AMOUNT
     FROM PAYMENT P
          INNER JOIN STUDENT_TEACHER_LESSON STL
             ON STL.ID = P.STUDENT_TEACHER_LESSON_ID
          INNER JOIN STUDENT S
             ON STL.STUDENT_ID = S.ID
          INNER JOIN TEACHER_LESSON TL
             ON STL.TEACHER_LESSON_ID = TL.ID
          INNER JOIN TEACHER T
             ON TL.TEACHER_ID = T.ID
          INNER JOIN LESSON L
             ON TL.LESSON_ID = L.ID
    WHERE P.ACTIVE = 1;

SELECT * FROM PAYMENT_VIEW;


SELECT ROWNUM ID, S.*
  FROM (SELECT NAME, SURNAME FROM STUDENT
        UNION
        SELECT NAME, SURNAME FROM TEACHER) S;

SELECT NAME, SURNAME FROM STUDENT
UNION ALL
SELECT NAME, SURNAME FROM TEACHER;

