/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package az.mycompany.course.gui;

import az.mycompany.course.model.Lesson;
import az.mycompany.course.model.Payment;
import az.mycompany.course.model.Student;
import az.mycompany.course.model.StudentTeacherLesson;
import az.mycompany.course.model.Teacher;
import az.mycompany.course.model.TeacherLesson;
import az.mycompany.course.service.LessonService;
import az.mycompany.course.service.PaymentService;
import az.mycompany.course.service.StudentService;
import az.mycompany.course.service.TeacherService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class NewPaymentFrame extends javax.swing.JFrame {

    private boolean a = false;
    private StudentService studentService;
    private TeacherService teacherService;
    private LessonService lessonService;
    private PaymentService paymentService;

    /**
     * Creates new form NewPaymentFrame
     */
    NewPaymentFrame(StudentService studentService, LessonService lessonService, TeacherService teacherService, PaymentService paymentService) {
        try {
            initComponents();
            this.studentService = studentService;
            this.teacherService = teacherService;
            this.lessonService = lessonService;
            this.paymentService = paymentService;
            showStudentData();
            showLessonData(lessonService.getLessonList());
            showTeacherData(teacherService.getTeacherList());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentCmb = new javax.swing.JComboBox<>();
        teacherCmb = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lessonCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Student");

        jLabel2.setText("Lesson");

        jLabel3.setText("Teacher");

        studentCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
        studentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCmbActionPerformed(evt);
            }
        });

        teacherCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));
        teacherCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherCmbActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");

        jLabel4.setText("Amount");

        jLabel5.setText("AZN");

        lessonCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lesson" }));
        lessonCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addGap(34, 34, 34)
                        .addComponent(clearBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacherCmb, 0, 226, Short.MAX_VALUE)
                            .addComponent(amountTxt)
                            .addComponent(lessonCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessonCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            Student student = (Student) studentCmb.getSelectedItem();
            Teacher teacher = (Teacher) teacherCmb.getSelectedItem();
            Lesson lesson = (Lesson) lessonCmb.getSelectedItem();
            Float amount = Float.valueOf(amountTxt.getText());
            TeacherLesson teacherLesson = teacherService.getTeacherLessonByTeacherAndLessonId(teacher.getId(), lesson.getId());
            StudentTeacherLesson studentTeacherLesson = studentService.getStudentTeacherLessonById(student.getId(), teacherLesson.getId());
            Payment payment = new Payment();
            payment.setStudentTeacherLesson(studentTeacherLesson);
            payment.setAmount(amount);
            paymentService.addPayment(payment);
            JOptionPane.showMessageDialog(null, "Successfully added");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void studentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCmbActionPerformed
        try {
            Student student = (Student) studentCmb.getSelectedItem();
            List<Lesson> lessonList = lessonService.getLessonByStudentId(student.getId());
            showLessonData(lessonList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_studentCmbActionPerformed

    private void teacherCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherCmbActionPerformed

    }//GEN-LAST:event_teacherCmbActionPerformed

    private void lessonCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonCmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lessonCmb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> studentCmb;
    private javax.swing.JComboBox<String> teacherCmb;
    // End of variables declaration//GEN-END:variables

    private void showStudentData() {
        try {
            List<Student> listStudent = studentService.getStudentList();
            DefaultComboBoxModel model = (DefaultComboBoxModel) studentCmb.getModel();
            for (Student student : listStudent) {
                model.addElement(student);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showTeacherData(List<Teacher> teacherlist) {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) teacherCmb.getModel();
            model.addElement("Select Teacher");
            model.removeAllElements();
            for (Teacher teacher : teacherlist) {
                model.addElement(teacher);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showLessonData(List<Lesson> lessonList) {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) lessonCmb.getModel();
            model.removeAllElements();
            model.addElement("Select Lesson");
            for (Lesson lesson : lessonList) {
                model.addElement(lesson);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
